/**************************************************************************************************\
 *** 
 *** Simulink model       : TestModel_Systeme_Habitacle
 *** TargetLink subsystem : TestModel_Systeme_Habitacle/FONCTION_HABITACLE
 *** Codefile             : FONCTION_HABITACLE.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2019-12-03 17:18:22
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.3\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.3\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.3 from 26-Oct-2017
 *** Code generator version  : Build Id 4.3.0.25 from 2017-10-26 16:41:23
\**************************************************************************************************/

#ifndef FONCTION_HABITACLE_H
#define FONCTION_HABITACLE_H

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "tl_basetypes.h"

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/


struct tag_SIBFS_Chart_a_tp {
   unsigned int Ca2_Clignotement : 1;
   unsigned int Ca3_Reset : 1;
   unsigned int Ca4_Eteindre : 1;
   unsigned int Ca5_Allumer : 1;
   unsigned int Ca6_CounterInitialisation : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

struct tag_SIBFS_Chart_a_tp_a {
   unsigned int Ca10_TouchAction : 1;
   unsigned int Ca8_Initialisation : 1;
   unsigned int Ca9_Counter2 : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 16
\**************************************************************************************************/
extern Int16 Sa1_Brake_Input; /* LSB: 0.09 OFF: 0 MIN/MAX: -100 .. 100 */

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\**************************************************************************************************/
extern Int8 Sa1_Indicator_Input; /* LSB: 2^0 OFF: 0 MIN/MAX: -1 .. 1 */
extern Bool Sa1_Warning_Input;
extern Bool Sa1_brakeSignal;
extern Bool Sa1_leftIndicatorSignal;
extern Bool Sa1_rightIndicatorSignal;

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   GlobalStep: Default function class for not static model step functions
\**************************************************************************************************/

// macro for Arduino compilation
#ifdef __cplusplus
extern "C" {
#endif

extern void FONCTION_HABITACLE(void);

#ifdef __cplusplus
}
#endif

#endif /* FONCTION_HABITACLE_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/