/**************************************************************************************************\
 *** 
 *** Simulink model       : TestModel_Systeme_Habitacle
 *** TargetLink subsystem : TestModel_Systeme_Habitacle/FONCTION_HABITACLE
 *** Codefile             : FONCTION_HABITACLE.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2019-12-03 17:18:22
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.3\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.3\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1            FONCTION_HABITACLE
 *** Sa2            FONCTION_HABITACLE/FONCTION_CLIGNOTANT
 *** Sa3            FONCTION_HABITACLE/FONCTION_FREINAGE
 *** Sa4            FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT
 *** Sa5            FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE
 *** Sa6            FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION
 *** Sa7            FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/DETECTION_FREINAGE_URGENCE
 *** Sa8            FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMANDE
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** Ca0            TestModel_Systeme_Habitacle                     
 *** Ca1            FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_G
 ***                ENERATION/Chart                                 
 *** Ca2            FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_G
 ***                ENERATION/Chart.Clignotement                    
 *** Ca3            FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_G
 ***                ENERATION/Chart.Clignotement.Reset              
 *** Ca4            FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_G
 ***                ENERATION/Chart.Clignotement.Eteindre           
 *** Ca5            FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_G
 ***                ENERATION/Chart.Clignotement.Allumer            
 *** Ca6            FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_G
 ***                ENERATION/Chart.CounterInitialisation           
 *** Ca7            FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart  
 *** Ca8            FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.
 ***                Initialisation                                  
 *** Ca9            FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.
 ***                Counter2                                        
 *** Ca10           FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.
 ***                TouchAction                                     
 *** 
 *** TargetLink version      : 4.3 from 26-Oct-2017
 *** Code generator version  : Build Id 4.3.0.25 from 2017-10-26 16:41:23
\**************************************************************************************************/

#ifndef FONCTION_HABITACLE_C
#define FONCTION_HABITACLE_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "tl_defines_a.h"
#include "FONCTION_HABITACLE.h"
#include "dsfxp.h"

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 16
\**************************************************************************************************/
Int16 Sa1_Brake_Input; /* LSB: 0.09 OFF: 0 MIN/MAX: -100 .. 100 */

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\**************************************************************************************************/
Int8 Sa1_Indicator_Input; /* LSB: 2^0 OFF: 0 MIN/MAX: -1 .. 1 */
Bool Sa1_Warning_Input;
Bool Sa1_brakeSignal;
Bool Sa1_leftIndicatorSignal;
Bool Sa1_rightIndicatorSignal;

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      FONCTION_HABITACLE
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void FONCTION_HABITACLE(void)
{
   /* SFStaticLocalInit: Default storage class for static local variables with initvalue | Width: 16
    */
   static UInt16 Ca1_clock_count = 0;
   static UInt16 Ca7_ctr2 = 0;

   /* SFStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
   */
   static Bool Ca1_indicatorSignal = 0;
   static Int8 Ca7_touchActivation = 0;

   /* SFStaticLocalInit: Default storage class for static local variables with initvalue | Width: N.
   A. */
   static struct tag_SIBFS_Chart_a_tp SIBFS_Chart_a = {
      0, /* Ca2_Clignotement: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
      0, /* Ca3_Reset: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
      0, /* Ca4_Eteindre: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
      0, /* Ca5_Allumer: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
      0 /* Ca6_CounterInitialisation: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   }; /* Description: Structure containing bitfields for Stateflow chart  */
   static struct tag_SIBFS_Chart_a_tp_a SIBFS_Chart_a_a = {
      0, /* Ca10_TouchAction: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
      0, /* Ca8_Initialisation: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
      0 /* Ca9_Counter2: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   }; /* Description: Structure containing bitfields for Stateflow chart  */

   /* SLLocal: Default storage class for local variables | Width: 8 */
   Bool Sa2_Logical_Operator;
   Bool Sa4_Logical_Operator;
   Bool Sa4_Logical_Operator1;
   Bool Sa4_Logical_Operator5;
   Bool Sa8_Relational_Operator;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 16
    */
   static Int16 X_Sa7_Unit_Delay = 0; /* LSB: 2^-7 OFF: 0 MIN/MAX: -256 .. 255.9921875 */
   static Int16 X_Sa8_Unit_Delay1 = 300;

   /* TargetLink outport: FONCTION_HABITACLE/brakeSignal
      # combined # Relational: FONCTION_HABITACLE/FONCTION_FREINAGE/Relational Operator */
   Sa1_brakeSignal = Sa1_Brake_Input >= 56 /* 5. */;
   /* Begin execution of chart FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart */
   if (SIBFS_Chart_a_a.Ca8_Initialisation) {
      /* Begin execution of state FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Initialisation */
      if (Sa1_Indicator_Input != 0) {
         /* State transition from FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Initialisation to F
            ONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Counter2 */
         SIBFS_Chart_a_a.Ca8_Initialisation = 0;
         Ca7_touchActivation = Sa1_Indicator_Input;
         SIBFS_Chart_a_a.Ca9_Counter2 = 1;
         Ca7_ctr2 = Ca7_ctr2 + 1;
      }
      /* End execution of state FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Initialisation */
   }
   else {
      if (SIBFS_Chart_a_a.Ca9_Counter2) {
         /* Begin execution of state FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Counter2 */
         if ((Ca7_ctr2 > 50) && (Sa1_Indicator_Input == 0)) {
            /* State transition from FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Counter2 to FONC
               TION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Initialisation */
            SIBFS_Chart_a_a.Ca9_Counter2 = 0;
            SIBFS_Chart_a_a.Ca8_Initialisation = 1;
            Ca7_touchActivation = 0;
            Ca7_ctr2 = 0;
         }
         else {
            if ((Ca7_ctr2 <= 50) && (Sa1_Indicator_Input == 0)) {
               /* State transition from FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Counter2 to F
                  ONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.TouchAction */
               SIBFS_Chart_a_a.Ca9_Counter2 = 0;
               SIBFS_Chart_a_a.Ca10_TouchAction = 1;
               Ca7_ctr2 = Ca7_ctr2 + 1;
            }
            else {
               if ((Ca7_ctr2 > 51) && (Sa1_Indicator_Input != 0)) {
                  /* State transition from FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Counter2 t
                     o FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Counter2 */
                  Ca7_ctr2 = 51;
               }
               SIBFS_Chart_a_a.Ca9_Counter2 = 1;
               Ca7_ctr2 = Ca7_ctr2 + 1;
            }
         }
         /* End execution of state FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Counter2 */
      }
      else {
         if (SIBFS_Chart_a_a.Ca10_TouchAction) {
            /* Begin execution of state FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.TouchAction
            */
            if ((Ca7_ctr2 >= 300) || (Sa1_Indicator_Input != 0)) {
               /* State transition from FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.TouchAction t
                  o FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Initialisation */
               SIBFS_Chart_a_a.Ca10_TouchAction = 0;
               SIBFS_Chart_a_a.Ca8_Initialisation = 1;
               Ca7_touchActivation = 0;
               Ca7_ctr2 = 0;
            }
            else {
               /* State transition from FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.TouchAction t
                  o FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.TouchAction */
               SIBFS_Chart_a_a.Ca10_TouchAction = 1;
               Ca7_ctr2 = Ca7_ctr2 + 1;
            }
            /* End execution of state FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.TouchAction */
         }
         else {
            /* State transition to FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart.Initialisation */
            SIBFS_Chart_a_a.Ca8_Initialisation = 1;
            Ca7_touchActivation = 0;
            Ca7_ctr2 = 0;
         }
      }
   }
   /* End execution of chart FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Chart */

   /* Switch: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMANDE/Switch
      FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMANDE/Switch: Omitted comparis
      on with constant.
      # combined # Logical: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/DETECTION_FREINAGE_URGENC
      E/Logical Operator
      # combined # Relational: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/DETECTION_FREINAGE_URG
      ENCE/Relational Operator1
      # combined # Relational: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/DETECTION_FREINAGE_URG
      ENCE/Relational Operator
      # combined # Sum: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/DETECTION_FREINAGE_URGENCE/Su
      m */
   if ((((Int16) (Sa1_Brake_Input - ((Int16) ((((Int32) X_Sa7_Unit_Delay) * 25) / ((Int32) 288)))))
    >= 5 /* 0.4 */) && (Sa1_Brake_Input >= 167 /* 15. */)) {
      /* Switch: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMANDE/Switch
         # combined # Unit delay: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMA
         NDE/Unit Delay1 */
      X_Sa8_Unit_Delay1 = 0;
   }
   else {
      /* SLLocal: Default storage class for local variables | Width: 16 */
      Int16 Sa8_Sum;

      /* Sum: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMANDE/Sum */
      Sa8_Sum = (Int16) (X_Sa8_Unit_Delay1 + 1);

      /* Switch: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMANDE/Switch
         # combined # Saturation: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMA
         NDE/Saturation
         # combined # Unit delay: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMA
         NDE/Unit Delay1 */
      X_Sa8_Unit_Delay1 = C__I16SATI16_SATb(Sa8_Sum, 301, 0);
   }

   /* Unit delay: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/DETECTION_FREINAGE_URGENCE/Unit Del
      ay */
   X_Sa7_Unit_Delay = (Int16) ((((Int32) Sa1_Brake_Input) * 288) / ((Int32) 25));

   /* Relational: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMANDE/Relational O
      perator
      # combined # Unit delay: FONCTION_HABITACLE/TRAITEMENT_FREINAGE_URGENCE/TEMPORISATION_COMMANDE
      /Unit Delay1 */
   Sa8_Relational_Operator = X_Sa8_Unit_Delay1 < 300;

   /* Logical: FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Logical Operator5 */
   Sa4_Logical_Operator5 = Sa1_Warning_Input || Sa8_Relational_Operator;

   /* Logical: FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Logical Operator
      # combined # Relational: FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Relational Operator1 */
   Sa4_Logical_Operator = (1 == Ca7_touchActivation) || Sa4_Logical_Operator5;

   /* Logical: FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Logical Operator1
      # combined # Relational: FONCTION_HABITACLE/TRAITEMENT_CLIGNOTANT/Relational Operator */
   Sa4_Logical_Operator1 = Sa4_Logical_Operator5 || (Ca7_touchActivation == -1);

   /* Logical: FONCTION_HABITACLE/FONCTION_CLIGNOTANT/Logical Operator */
   Sa2_Logical_Operator = Sa4_Logical_Operator || Sa4_Logical_Operator1;
   /* Begin execution of chart FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart */
   if (SIBFS_Chart_a.Ca2_Clignotement) {
      /* Begin execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart.Cli
         gnotement */
      if (!(Sa2_Logical_Operator)) {
         /* State transition from FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart.Cli
            gnotement to FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart.CounterIniti
            alisation */
         if (SIBFS_Chart_a.Ca3_Reset) {
            SIBFS_Chart_a.Ca3_Reset = 0;
         }
         else {
            if (SIBFS_Chart_a.Ca4_Eteindre) {
               SIBFS_Chart_a.Ca4_Eteindre = 0;
            }
            else {
               SIBFS_Chart_a.Ca5_Allumer = 0;
            }
         }
         SIBFS_Chart_a.Ca2_Clignotement = 0;
         SIBFS_Chart_a.Ca6_CounterInitialisation = 1;
         Ca1_clock_count = 0;
         Ca1_indicatorSignal = 0;
      }
      else {
         if (SIBFS_Chart_a.Ca3_Reset) {
            /* SLLocal: Default storage class for local variables | Width: 16 */
            Int16 Sa6_Switch;

            /* Switch: FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Switch
               FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Switch: Omitted comparison w
               ith constant. */
            if (Sa8_Relational_Operator) {
               /* Switch: FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Switch */
               Sa6_Switch = 24;
            }
            else {
               /* Switch: FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Switch */
               Sa6_Switch = 49;
            }

            /* Begin execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Cha
               rt.Clignotement.Reset */

            /* FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart: Omitted comparison wi
               th constant. */
            if (Ca1_indicatorSignal && (((Int32) Ca1_clock_count) >= ((Int32) Sa6_Switch))) {
               /* State transition from FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Cha
                  rt.Clignotement.Reset to FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/
                  Chart.Clignotement.Eteindre */
               SIBFS_Chart_a.Ca3_Reset = 0;
               SIBFS_Chart_a.Ca4_Eteindre = 1;
               Ca1_indicatorSignal = 0;
               Ca1_clock_count = 0;
            }
            else {
               /* FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart: Omitted comparison
                   with constant. */
               if ((!(Ca1_indicatorSignal)) && (((Int32) Ca1_clock_count) >= ((Int32) Sa6_Switch)))
                {
                  /* State transition from FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/
                     Chart.Clignotement.Reset to FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENER
                     ATION/Chart.Clignotement.Allumer */
                  SIBFS_Chart_a.Ca3_Reset = 0;
                  SIBFS_Chart_a.Ca5_Allumer = 1;
                  Ca1_indicatorSignal = 1;
                  Ca1_clock_count = 0;
               }
               else {
                  if (((Int32) Ca1_clock_count) < ((Int32) Sa6_Switch)) {
                     /* State transition from FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATI
                        ON/Chart.Clignotement.Reset to FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL
                        _GENERATION/Chart.Clignotement.Reset */
                     SIBFS_Chart_a.Ca3_Reset = 1;
                     Ca1_clock_count = Ca1_clock_count + 1;
                  }
               }
            }
            /* End execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart
               .Clignotement.Reset */
         }
         else {
            if (SIBFS_Chart_a.Ca4_Eteindre) {
               /* Begin execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/
                  Chart.Clignotement.Eteindre */

               /* State transition from FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Cha
                  rt.Clignotement.Eteindre to FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATI
                  ON/Chart.Clignotement.Reset */
               SIBFS_Chart_a.Ca4_Eteindre = 0;
               SIBFS_Chart_a.Ca3_Reset = 1;
               Ca1_clock_count = Ca1_clock_count + 1;
               /* End execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Ch
                  art.Clignotement.Eteindre */
            }
            else {
               if (SIBFS_Chart_a.Ca5_Allumer) {
                  /* Begin execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATI
                     ON/Chart.Clignotement.Allumer */

                  /* State transition from FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/
                     Chart.Clignotement.Allumer to FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GEN
                     ERATION/Chart.Clignotement.Reset */
                  SIBFS_Chart_a.Ca5_Allumer = 0;
                  SIBFS_Chart_a.Ca3_Reset = 1;
                  Ca1_clock_count = Ca1_clock_count + 1;
                  /* End execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION
                     /Chart.Clignotement.Allumer */
               }
            }
         }
      }
      /* End execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart.Clign
         otement */
   }
   else {
      if (SIBFS_Chart_a.Ca6_CounterInitialisation) {
         /* Begin execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart.
            CounterInitialisation */
         if (Sa2_Logical_Operator) {
            /* State transition from FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart.
               CounterInitialisation to FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Cha
               rt.Clignotement */
            SIBFS_Chart_a.Ca6_CounterInitialisation = 0;
            SIBFS_Chart_a.Ca2_Clignotement = 1;

            /* State transition to FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart.Cl
               ignotement.Allumer */
            SIBFS_Chart_a.Ca5_Allumer = 1;
            Ca1_indicatorSignal = 1;
            Ca1_clock_count = 0;
         }
         /* End execution of state FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart.Co
            unterInitialisation */
      }
      else {
         /* State transition to FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart.Count
            erInitialisation */
         SIBFS_Chart_a.Ca6_CounterInitialisation = 1;
         Ca1_clock_count = 0;
         Ca1_indicatorSignal = 0;
      }
   }
   /* End execution of chart FONCTION_HABITACLE/FONCTION_CLIGNOTANT/SIGNAL_GENERATION/Chart */

   /* TargetLink outport: FONCTION_HABITACLE/rightIndicatorSignal
      # combined # Logical: FONCTION_HABITACLE/FONCTION_CLIGNOTANT/Logical Operator1 */
   Sa1_rightIndicatorSignal = Ca1_indicatorSignal && Sa4_Logical_Operator1;

   /* TargetLink outport: FONCTION_HABITACLE/leftIndicatorSignal
      # combined # Logical: FONCTION_HABITACLE/FONCTION_CLIGNOTANT/Logical Operator2 */
   Sa1_leftIndicatorSignal = Sa4_Logical_Operator && Ca1_indicatorSignal;
}

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#endif /* FONCTION_HABITACLE_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/